/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistRouteImport } from './routes/therapist'
import { Route as SosRouteImport } from './routes/sos'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AwarenessRouteImport } from './routes/awareness'
import { Route as IndexRouteImport } from './routes/index'

const TherapistRoute = TherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarenessRoute = AwarenessRouteImport.update({
  id: '/awareness',
  path: '/awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/sos': typeof SosRoute
  '/therapist': typeof TherapistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/sos': typeof SosRoute
  '/therapist': typeof TherapistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/sos': typeof SosRoute
  '/therapist': typeof TherapistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awareness'
    | '/community'
    | '/dashboard'
    | '/digital-twin'
    | '/sos'
    | '/therapist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awareness'
    | '/community'
    | '/dashboard'
    | '/digital-twin'
    | '/sos'
    | '/therapist'
  id:
    | '__root__'
    | '/'
    | '/awareness'
    | '/community'
    | '/dashboard'
    | '/digital-twin'
    | '/sos'
    | '/therapist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwarenessRoute: typeof AwarenessRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  SosRoute: typeof SosRoute
  TherapistRoute: typeof TherapistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapist': {
      id: '/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof TherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awareness': {
      id: '/awareness'
      path: '/awareness'
      fullPath: '/awareness'
      preLoaderRoute: typeof AwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwarenessRoute: AwarenessRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  SosRoute: SosRoute,
  TherapistRoute: TherapistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
